emails = ['helishah4.hs@gmail.com','dhruv.edu.doshi@gmail.com',
            'vivek23shah@gmail.com','nayansakihya25@gmail.com',
            'krupalpatel111098@gmail.com','prachi98kadam@gmail.com',
            'jainamdamanwala21@gmail.com','maitrid483@gmail.com',
            'kishanparmar903@gmail.com','shrenikmehta11@gmail.com',
            'devanshmehta966@hotmail.com','jeelkapadia3105@gmail.com',
            'bhattshivam23456@gmail.com','shreyppatel2005@gmail.com',
            'patelkushank.pk@gmail.com','dhavaldeshkar@gmail.com',
            'neelsoni183@gmail.com','harsh8121998@gmail.com',
            'helishah4.hs@gmail.com','sarthakpatel3@gmail.com',
            'ruchishah984@gmail.com','harshshah692@gmail.com',
            'rutvip98@gmail.com','dhuvadk@gmail.com',
            'pavangajjar131298@gmail.com','hardixerox2016@gmail.com',
            'vipulgorana@gmail.com','hardipatel689@gmail.com',
            'bansal.gajjar99@gmail.com','premsocet@gmail.com',
            'darshilshah.ce@gmail.com','tejas.chauhan112@gmail.com',
            'rahul.daiya.12999@gmail.com','snehajha367@gmail.com',
            'bhalaniyp98@gmail.com','pritidarji987@gmail.com',
            'anajalichaudhary4441@gmail.com','vashisth107@gmail.com',
            'slokejoshi@gmail.com','bhattjay804@gmail.com',
            'hridanshu.gadhvi@gmail.com','christiancececil409@gmail.com',
            'pathikdave3850@gmail.com','alimchandaniv@gmail.com',
            'dipenbhatt5369@gmail.com','vipulchetandarji@gmail.com',
            'mihirvchaudhari@gmail.com','aetesamchauhan@gmail.com',
            '1510helibhavsar@gmail.com','nchimnani29@gmail.com',
            'devangbaroliya@gmail.com','bhalaniyp98@gmail.com',
            'kaivilbrahmbhatt0805@gmail.com','Keyubrahmbhatt1@gmail.com',
            'ritikjoshi8460@gmail.com','Hardik1820borda@gmail.com',
            'honeybhavsar36@gmail.com','jishanshaikh10@gmail.com',
            'mahipal98.md@gmail.com','urveshdudhat09@gmail.com',
            'srushtigupta5@gmail.com','tirthdesai111920@gmail.com',
            'nikunjbhimani4151@gamil.com','Shaswatbhatt2@gmail.com',
            'vdkapadiya1998@gmail.com','rutvik.joshi@live.com',
            'trupesh789@gmail.com','raja9375bhagat@gmail.com',
            'Yashbkabariya@gmail.com','shaunakghachelia310@gmail.com',
            'Chaudharyurvesh@gmail.com','amankalal19@gmail.com',
            'satvik.it@socet.edu.in','satvik@socet.edu.in',
            'haresh.it@socet.edu.in','hemalpatel.it@socet.edu.in',
            'jaimindave.it@socet.edu.in','kinjalthakar.it@socet.edu.in',
            'sagarpatel.ce@socet.edu.in','sagarpatel.it@socet.edu.in',
            'manishsingh.ce@socet.edu.in','samarthmodi.ce@socet.edu.in',
            '','',
            '','',
            '','',
            '','',
            '','',
            '','',
            '','',
            '','',
            '','',
            '','',
            '','',


            
            ]

